### ISSUE TITLE
Can opus be decoded to PCM in sequential audio chunks? Currently, it only works when I decode the entire audio file stream.

### ISSUE THREAD

**Issue by TinoBaRo** [lostromb/concentus#51]
When I try to decode an entire FileStream it works perfectly fine:

```
        string basePath = Path.Combine(AppContext.BaseDirectory, "_opusAudioSources");
        string opusFilePath = Path.Combine(basePath, "testopus_01_updated.opus");
        string pcmFilePath = Path.Combine(basePath, "test_pcm_01.wav");
        // Convert Opus to PCM
        using (var opusInputStream = new FileStream(opusFilePath, FileMode.Open))
        using (var pcmOutputStream = new FileStream(pcmFilePath, FileMode.Create))
        {
            var converter = new OpusToPcmConverter();
            converter.ConvertOpusToPcm(opusInputStream, pcmOutputStream);
        }

public void ConvertOpusToPcm(FileStream opusInputStream, FileStream pcmOutputStream)
    {
        try
        {
            using (OpusDecoder decoder = (OpusDecoder)OpusCodecFactory.CreateDecoder(_inputSampleRate, _channels))
            {
                OpusOggReadStream oggStreamReader = new OpusOggReadStream(decoder, opusInputStream);
                using (BinaryWriter writer = new BinaryWriter(pcmOutputStream))
                {
                    WriteWavHeader(writer, _channels, _inputSampleRate, 16, 0);
                    long dataChunkPosition = writer.BaseStream.Position;
                    // format for the output PCM data
                    var outputFormat = new WaveFormat(_outputSampleRate, 16, _channels);
                    while (oggStreamReader.HasNextPacket)
                    {
                        byte[] opusPacket = oggStreamReader.ReadNextRawPacket();
                        float[] pcmSamples = new float[960 * _channels];

                        // Decode the Opus data to PCM
                        int decodedSamples = decoder.Decode(opusPacket.AsSpan(), pcmSamples.AsSpan(), _inputSampleRate, false);
                       
                        // further processing then writing to pcmOutputStream....
 
```
                   
                        
However, when I try to do it by audio chunks it doesn't work and only a fraction of the data gets decoded. Sometimes it's only the first 3 seconds, sometimes it is random segments of audio, mostly depending on the buffer size.
```

var converter = new OpusToPcmConverter();
using (var opusStream = new FileStream(opusFilePath, FileMode.Open, FileAccess.Read))
{
    byte[] buffer = new byte[8192];
    int bytesRead;
    while ((bytesRead = await opusStream.ReadAsync(buffer)) > 0)
    {
        byte[] audioChunk = new byte[bytesRead];
        Array.Copy(buffer, audioChunk, bytesRead);

        byte[] pcmChunk = converter.ConvertOpusToPcm(new MemoryStream(audioChunk));
    }
}

public byte[] ConvertOpusToPcm(Stream opusStream)
{
    using (var pcmOutputStream = new MemoryStream())
    {
        try
        {
            using (OpusDecoder decoder = (OpusDecoder)OpusCodecFactory.CreateDecoder(_inputSampleRate, _channels))
            {
                opusStream.Position = 0;
                OpusOggReadStream oggStreamReader = new OpusOggReadStream(decoder, opusStream);

                using (BinaryWriter writer = new BinaryWriter(pcmOutputStream))
                {
                    // format for the output PCM data
                    var outputFormat = new WaveFormat(_outputSampleRate, 16, _channels);

                    while (oggStreamReader.HasNextPacket)
                    {
                        byte[] opusPacket = oggStreamReader.ReadNextRawPacket();
                        float[] pcmSamples = new float[960 * _channels];
                        // Decode the Opus data to PCM
                        int decodedSamples = decoder.Decode(opusPacket.AsSpan(), pcmSamples.AsSpan(), _inputSampleRate, false);
                        
                        // further processing then returning byte[] ... 
                  
```
 
                        
**Is this type of operation supported currently?**
Thanks a lot in advance.

**Comment by lostromb** [comment]
I'm a little confused by your question since your sample code has a loop that..... does exactly what you're asking?
```csharp
while (oggStreamReader.HasNextPacket)
    short[] decodedFrame = oggStreamReader.DecodeNextPacket();
    // You now have a 20ms chunk of audio, read sequentially
```

The reason you can't take a slice of the .opus file, put it into a buffer and read it with `converter.ConvertOpusToPcm(new MemoryStream(audioChunk));` is because of the [OggOpus](https://wiki.xiph.org/OggOpus) format..... uh..... you can read the spec but I'll give the short explanation. An opus file is an ogg file that contains at least one data stream. The stream consists of two special header blocks - `OpusHead` and `OpusTags` - followed by any number of encoded audio data packets. OpusHead is essential to know the channel layout of the encoded audio, among other things, so the `OpusOggReadStream` expects to find that first. After you have the header info, _then_ random seeking and slicing is possible within the audio data stream. So your second sample code doesn't work because the slices of the input file are just random audio data with no `OpusHead` to identify them.

It would help to know more about your use case, but I would guess you're trying to do some kind of streaming setup where you want audio playback to start before the entire stream is downloaded? If that's the case, you could implement some kind of read-write pipe that implements `Stream` and use that as your audio source, writing data to the pipe as it becomes available.

**Comment by TinoBaRo** [comment]
Thanks so much for the detailed answer. I was able to make it work by passing an entire Ogg Page with the necessary headers one at a time.

However, something that I have realized is that it is possible that an Ogg page has a partial packet at the end of the page, and the following page will contain the remainder of that packet.

![image](https://github.com/user-attachments/assets/2a07ea7d-a073-469f-8f8f-11a3dd9a5a4e)

Is Concentus.Oggfile handling this case? Or will this packet be lost.

**Comment by lostromb** [comment]
> If I'm passing one page at a time to OpusOggReadStream, is the above case being handled or will this packet be lost?

Good question.... generally I don't consider this a big problem for Opus because packets are usually just a few dozen bytes and would fill up the page's lacing table (255 packets) before hitting the maximum page size (64Kb), so it would only ever potentially "overflow" a page at bitrates above 100 kbit/s. The `Concentus.Oggfile` encoder will not produce streams with opus packets that span pages, just for simplicity, but other encoders could theoretically do it because the ogg spec allows it.

For your question, I guess the answer depends on how you are producing the pages. If you are just pulling existing pages out of a stream.... for example, you have stream 0 with page 0 and page 1, and a packet that spans those two pages, and then convert that into stream 0 with page 0, and then stream 1 with page 1, and the pages are no longer continuations of each other, then you have an invalid stream because you have a packet straddling the boundary into a page which no longer exists because they're on separate streams.

If you are taking the opus _packets_ out of the stream, for example with `byte[] opusPacket = oggStreamReader.ReadNextRawPacket();`, and then putting those _packets_ each into a new page, then that should work because you would be creating valid streams and valid pages, each stream would just be incredibly short. I hope that makes sense.

Again, I do have to ask: what exactly are you trying to accomplish? Are you doing real-time streaming? Because I will warn you that OggOpus **does not** handle real-time streaming very well. You have to choose between either a huge data overhead - as you've seen, creating all of these new streams and new page headers and checksums just to send a few packets at a time, or you will have several seconds of lag (with opus it's as much as 5 seconds delay) because of page buffering as the encoder is slowly filling up a page before sending. There are probably better ways to do whatever it is you're trying to do.

**Comment by TinoBaRo** [comment]
Thanks a lot for the detailed answer. Yes I'm doing real-time streaming. Given the limitation, I've decided to use concentus purely for decoding a packet. For dealing with pages I'm using libogg directly.

**Comment by lostromb** [comment]
The recommended way to do real-time streams (per the Opus developers) is to either use [RTP](https://www.rfc-editor.org/rfc/rfc7587) for framing, or to use your own self-delimited packets using the [Opus frame-length representation](https://www.rfc-editor.org/rfc/rfc6716#section-3.2.1). That is, to send a 110 byte packet, prefix the opus data with `0x6E`. To send a 750 byte packet, prefix the Opus data with `0xFE 7C`
